
AtlasOptions = {
	["AtlasSortBy"] = 1,
	["AtlasCtrl"] = false,
	["AtlasAlpha"] = 1,
	["AtlasButtonRadius"] = 78,
	["AtlasAutoSelect"] = false,
	["AtlasRightClick"] = false,
	["AtlasClamped"] = true,
	["AtlasAcronyms"] = true,
	["AtlasType"] = 1,
	["AtlasButtonShown"] = true,
	["AtlasVersion"] = "1.18.2",
	["AtlasButtonPosition"] = 26,
	["AtlasBossDesc"] = true,
	["AtlasZone"] = 1,
	["AtlasScale"] = 1,
	["AtlasBossDescScale"] = 0.8999999761581421,
	["AtlasLocked"] = false,
}
