
AutoProfitX2DB = {
	["global"] = {
		["Auchindoun"] = {
			["Promitto"] = {
				["exceptionList"] = {
					["76565"] = true,
					["52170"] = true,
					["76560"] = true,
					["76520"] = true,
					["76566"] = true,
					["76567"] = true,
					["76512"] = true,
					["76548"] = true,
					["76540"] = true,
					["76538"] = true,
					["76562"] = true,
					["76564"] = true,
					["76505"] = true,
					["76569"] = true,
					["76508"] = true,
					["76504"] = true,
					["52087"] = true,
					["76536"] = true,
					["76568"] = true,
					["76509"] = true,
					["76502"] = true,
					["76549"] = true,
				},
			},
			["Aset"] = {
				["exceptionList"] = {
					["76562"] = true,
					["76540"] = true,
					["76564"] = true,
					["52170"] = true,
					["76569"] = true,
					["76520"] = true,
					["52087"] = true,
					["76567"] = true,
					["76509"] = true,
					["76505"] = true,
				},
			},
		},
	},
	["profileKeys"] = {
		["Kernelpanic - Auchindoun"] = "Kernelpanic - Auchindoun",
		["Quasar - Whisperwind"] = "Quasar - Whisperwind",
		["Chukk - Auchindoun"] = "Chukk - Auchindoun",
		["Deadset - Auchindoun"] = "Deadset - Auchindoun",
		["Aset - Mannoroth"] = "Aset - Mannoroth",
		["Tyl - Whisperwind"] = "Tyl - Whisperwind",
		["Notevilatall - Whisperwind"] = "Notevilatall - Whisperwind",
		["Sadr - Auchindoun"] = "Sadr - Auchindoun",
		["Gogogogogog - Auchindoun"] = "Gogogogogog - Auchindoun",
		["Promitto - Auchindoun"] = "Promitto - Auchindoun",
		["Pulari - Auchindoun"] = "Pulari - Auchindoun",
		["Mageboxone - Auchindoun"] = "Mageboxone - Auchindoun",
		["Deadset - Whisperwind"] = "Deadset - Whisperwind",
		["Aonah - Auchindoun"] = "Aonah - Auchindoun",
		["Aonah - Whisperwind"] = "Aonah - Whisperwind",
		["Fatset - Auchindoun"] = "Fatset - Auchindoun",
		["Profitmargin - Mannoroth"] = "Profitmargin - Mannoroth",
		["Oxshield - Auchindoun"] = "Oxshield - Auchindoun",
		["Wezen - Auchindoun"] = "Wezen - Auchindoun",
		["Charlls - Whisperwind"] = "Charlls - Whisperwind",
		["Gacrux - Auchindoun"] = "Gacrux - Auchindoun",
		["Huntboxone - Auchindoun"] = "Huntboxone - Auchindoun",
		["Pooshield - Thrall"] = "Pooshield - Thrall",
		["Profitmargin - Whisperwind"] = "Profitmargin - Whisperwind",
		["Karrl - Auchindoun"] = "Karrl - Auchindoun",
		["Lockboxone - Auchindoun"] = "Lockboxone - Auchindoun",
		["Aset - Auchindoun"] = "Aset - Auchindoun",
		["Promitto - Whisperwind"] = "Promitto - Whisperwind",
		["Fatset - Whisperwind"] = "Fatset - Whisperwind",
		["Pulari - Whisperwind"] = "Pulari - Whisperwind",
	},
}
AutoProfitX2_ExceptionlistVersion = nil
AutoProfitX2_Settings = nil
