
DataStore_CharactersDB = {
	["profileKeys"] = {
		["Chukk - Auchindoun"] = "Chukk - Auchindoun",
		["Aonah - Auchindoun"] = "Aonah - Auchindoun",
	},
	["global"] = {
		["Characters"] = {
			["Default.Auchindoun.Aonah"] = {
				["XPMax"] = 12267000,
				["played"] = 6015809,
				["guildRankName"] = "Guild Master",
				["isResting"] = 1,
				["lastUpdate"] = 1317995949,
				["class"] = "Mage",
				["race"] = "Draenei",
				["level"] = 85,
				["XP"] = 471,
				["RestXP"] = 0,
				["money"] = 49618951,
				["gender"] = 3,
				["englishClass"] = "MAGE",
				["guildRankIndex"] = 0,
				["guildName"] = "Terokkar Florist",
				["subZone"] = "",
				["faction"] = "Alliance",
				["englishRace"] = "Draenei",
				["name"] = "Aonah",
				["lastLogoutTimestamp"] = 1317995949,
				["zone"] = "Stormwind City",
			},
			["Default.Auchindoun.Chukk"] = {
				["XPMax"] = 12267000,
				["played"] = 3271727,
				["guildRankName"] = "Casual Member",
				["isResting"] = 1,
				["lastUpdate"] = 1317877949,
				["class"] = "Priest",
				["race"] = "Human",
				["level"] = 85,
				["XP"] = 2431,
				["RestXP"] = 0,
				["money"] = 999582,
				["gender"] = 2,
				["englishClass"] = "PRIEST",
				["name"] = "Chukk",
				["faction"] = "Alliance",
				["subZone"] = "",
				["guildName"] = "Open Ticket",
				["englishRace"] = "Human",
				["guildRankIndex"] = 6,
				["lastLogoutTimestamp"] = 1317877949,
				["zone"] = "Stormwind City",
			},
		},
	},
}
