
DataStore_CharactersDB = {
	["profileKeys"] = {
		["Chukk - Auchindoun"] = "Chukk - Auchindoun",
		["Aonah - Auchindoun"] = "Aonah - Auchindoun",
	},
	["global"] = {
		["Characters"] = {
			["Default.Auchindoun.Aonah"] = {
				["XPMax"] = 12267000,
				["played"] = 5981204,
				["guildRankName"] = "Guild Master",
				["isResting"] = 1,
				["lastUpdate"] = 1317247950,
				["class"] = "Mage",
				["race"] = "Draenei",
				["level"] = 85,
				["XP"] = 471,
				["RestXP"] = 0,
				["money"] = 37228896,
				["gender"] = 3,
				["zone"] = "Stormwind City",
				["subZone"] = "Trade District",
				["guildRankIndex"] = 0,
				["name"] = "Aonah",
				["faction"] = "Alliance",
				["englishRace"] = "Draenei",
				["guildName"] = "Terokkar Florist",
				["lastLogoutTimestamp"] = 1317247950,
				["englishClass"] = "MAGE",
			},
			["Default.Auchindoun.Chukk"] = {
				["XPMax"] = 12267000,
				["played"] = 3267367,
				["guildRankName"] = "Casual Member",
				["isResting"] = 1,
				["lastUpdate"] = 1317102029,
				["class"] = "Priest",
				["race"] = "Human",
				["level"] = 85,
				["XP"] = 2431,
				["RestXP"] = 0,
				["money"] = 999912,
				["gender"] = 2,
				["zone"] = "Stormwind City",
				["subZone"] = "Old Town",
				["name"] = "Chukk",
				["guildRankIndex"] = 6,
				["guildName"] = "Open Ticket",
				["englishRace"] = "Human",
				["faction"] = "Alliance",
				["lastLogoutTimestamp"] = 1317102029,
				["englishClass"] = "PRIEST",
			},
		},
	},
}
