
TradeSkillMaster_MailingDB = {
	["profiles"] = {
		["Default"] = {
		},
	},
	["profileKeys"] = {
		["Kernelpanic - Auchindoun"] = "Default",
		["Quasar - Whisperwind"] = "Default",
		["Chukk - Auchindoun"] = "Default",
		["Deadset - Auchindoun"] = "Default",
		["Aset - Mannoroth"] = "Default",
		["Sadr - Auchindoun"] = "Default",
		["Gogogogogog - Auchindoun"] = "Default",
		["Promitto - Auchindoun"] = "Default",
		["Mageboxone - Auchindoun"] = "Default",
		["Aonah - Auchindoun"] = "Default",
		["Fatset - Auchindoun"] = "Default",
		["Aonah - Whisperwind"] = "Default",
		["Promitto - Whisperwind"] = "Default",
		["Charlls - Whisperwind"] = "Default",
		["Profitmargin - Mannoroth"] = "Default",
		["Gacrux - Auchindoun"] = "Default",
		["Aset - Auchindoun"] = "Default",
		["Profitmargin - Whisperwind"] = "Default",
		["Wezen - Auchindoun"] = "Default",
		["Lockboxone - Auchindoun"] = "Default",
		["Karrl - Auchindoun"] = "Default",
		["Deadset - Whisperwind"] = "Default",
		["Pulari - Auchindoun"] = "Default",
		["Tyl - Whisperwind"] = "Default",
		["Pulari - Whisperwind"] = "Default",
	},
	["factionrealm"] = {
		["Alliance - Whisperwind"] = {
			["mailTargets"] = {
				"profitmargin", -- [1]
				"charlls", -- [2]
				"promitto", -- [3]
				"pulari", -- [4]
			},
			["mailItems"] = {
				[72235] = "pulari",
				[72237] = "pulari",
				[83804] = "charlls",
				[83806] = "charlls",
				["shoulder enchants"] = "profitmargin",
				[72092] = "promitto",
				["truegold"] = "profitmargin",
				["mid tier scrolls"] = "profitmargin",
				[72234] = "pulari",
				["rare gems"] = "profitmargin",
				[83803] = "charlls",
				["low tier scrolls"] = "profitmargin",
				[72093] = "promitto",
				[79010] = "pulari",
				["high tier scrolls"] = "profitmargin",
				["de gear"] = "charlls",
				["glyphs"] = "profitmargin",
				[76141] = "promitto",
				["cut uncommon gems"] = "profitmargin",
			},
		},
		["Alliance - Mannoroth"] = {
			["mailTargets"] = {
				"profitmargin", -- [1]
				"aset", -- [2]
			},
			["mailItems"] = {
				[72092] = "aset",
				["rare gems"] = "profitmargin",
			},
		},
		["Alliance - Auchindoun"] = {
			["mailTargets"] = {
				"pulari", -- [1]
				"chukk", -- [2]
				"promitto", -- [3]
				"deadset", -- [4]
				"kernelpanic", -- [5]
				"mawl", -- [6]
				"aonah", -- [7]
			},
			["test"] = 2,
			["mailItems"] = {
				[74850] = "aonah",
				["glyphs"] = "aonah",
				[52306] = "chukk",
				[52183] = "deadset",
				[52314] = "chukk",
				[52191] = "aonah",
				[52195] = "aonah",
				[52326] = "promitto",
				["old herbs"] = "aonah",
				[52207] = "aonah",
				[52719] = "aonah",
				[52985] = "pulari",
				[6037] = "promitto",
				["belt buckles"] = "aonah",
				[55037] = "chukk",
				[74248] = "aonah",
				[8846] = "pulari",
				[3355] = "pulari",
				[36904] = "pulari",
				[8838] = "pulari",
				[43126] = "pulari",
				[3356] = "pulari",
				[39341] = "pulari",
				[52180] = "promitto",
				[52307] = "chukk",
				[3357] = "pulari",
				["low tier scrolls"] = "aonah",
				["red gems"] = "aonah",
				[52192] = "aonah",
				[3358] = "pulari",
				[52327] = "promitto",
				[51950] = "promitto",
				["essences"] = "aonah",
				[41163] = "promitto",
				[90904] = "chukk",
				[53010] = "aonah",
				["high tier scrolls"] = "aonah",
				[52328] = "aonah",
				["rare gems"] = "aonah",
				[52181] = "promitto",
				[72235] = "pulari",
				[72988] = "aonah",
				[72234] = "pulari",
				["uncommon gems"] = "aonah",
				["misc blue gear"] = "aonah",
				["epic gems"] = "aonah",
				[43120] = "pulari",
				[36901] = "pulari",
				[37921] = "pulari",
				[53038] = "deadset",
				["cut uncommon gems"] = "aonah",
				[65365] = "promitto",
				["shards"] = "aonah",
				[13466] = "pulari",
				[39342] = "pulari",
				[74849] = "aonah",
				[72092] = "aset",
				[52308] = "chukk",
				[52185] = "aset",
				[52316] = "chukk",
				[52193] = "aonah",
				[13463] = "pulari",
				[13464] = "pulari",
				[52213] = "aonah",
				["leg armor"] = "aonah",
				[52721] = "aonah",
				[74839] = "aonah",
				[74847] = "aonah",
				[74833] = "aonah",
				[72093] = "aset",
				[56551] = "aonah",
				["worthless blues"] = "aonah",
				[75014] = "aonah",
				[90905] = "chukk",
				[83793] = "chukk",
				["dust"] = "aonah",
				[58480] = "aonah",
				["truegold"] = "aonah",
				[52325] = "promitto",
				[52310] = "chukk",
				[52182] = "promitto",
				[83794] = "chukk",
				[54849] = "promitto",
				[2452] = "pulari",
				[39970] = "pulari",
				[72237] = "pulari",
				[39343] = "pulari",
				[52555] = "aonah",
				[52178] = "aonah",
				[52309] = "chukk",
				[52186] = "promitto",
				[3818] = "pulari",
				["volatiles"] = "aonah",
				["outland motes"] = "aonah",
				[52329] = "aonah",
				[52206] = "aonah",
				[68729] = "kernelpanic",
				[52722] = "aonah",
				[52983] = "pulari",
				[52984] = "pulari",
				[52988] = "pulari",
				["mid tier scrolls"] = "aonah",
				[4625] = "pulari",
				[52492] = "chukk",
				[52177] = "aset",
				[74846] = "aonah",
				["meta gems"] = "aonah",
				[52312] = "chukk",
				[52212] = "aonah",
				[52188] = "promitto",
				[43122] = "pulari",
				[36903] = "pulari",
				[36907] = "pulari",
				[52179] = "promitto",
				["misc shit"] = "aonah",
			},
		},
	},
}
